ci/cd:
  - .github/workflows/*
  - .github/*.yml
rust:
  - src/*
  - src/**/*
protobuf:
  - proto/*
  - proto/**/*
deploy-prod:
  - master
deploy-staging:
  - staging
deploy-dev:
  - dev
documentation:
  - .github/ISSUE_TEMPLATE/*
  - pull_request_template.md
data:
  - *.csv