ci/cd:
  - .github/*
  - .github/**/*
  - scripts/*
  - scripts/**/*
rust:
  - src/*
  - src/**/*
data:
  - migrations/*
protobuf:
  - proto/*
  - proto/**/*
deploy-prod:
  - master
deploy-staging:
  - staging
deploy-dev:
  - dev
