

type: google.api.Service
config_version: 3

name: stationapi.endpoints.trainlcd.cloud.goog

title: StationAPI
apis:
- name: app.traincd.grpc.StationAPI
usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true