[package]
name = "stationapi"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "stationapi"
path = "src/main.rs"

[dependencies]
tracing-subscriber = { version = "0.3.17", features = ["tracing-log", "fmt"] }
async-trait = "0.1.68"
dotenv = "0.15.0"
prost = "0.12.0"
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "tls-native-tls",
    "mysql",
    "bigdecimal",
] }
tokio = { version = "1.28.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.10.1"
tonic-web = "0.10.1"
tracing = "0.1.37"
mockall = "0.11.2"
bigdecimal = { version = "0.3.0", features = ["serde"] }
serde = { version = "1.0.162", features = ["derive"] }
percent-encoding = "2.2.0"
url = "2.3.1"
log = "0.4.17"
anyhow = "1.0.71"
thiserror = "1.0.40"
rand = "0.8.5"
moka = { version = "0.11", features = ["future"] }
hyper = "0.14.27"
tower = "0.4.13"
http = "0.2.9"

[build-dependencies]
tonic-build = { version = "0.10.1", features = ["prost"] }
