[package]
name = "stationapi"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "stationapi-server"
path = "src/server.rs"

[dependencies]
async-trait = "0.1.68"
dotenv = "0.15.0"
prost = "0.11.9"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "mysql", "macros", "bigdecimal" ] }
tokio = { version = "1.28.0", features = ["full"] }
tonic = "0.9.2"
tonic-web = "0.9.2"
tower-http = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
mockall = "0.11.2"
bigdecimal = {version = "0.3.0", features = ["serde"] }
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"

[build-dependencies]
tonic-build = "0.9.2"
prost-build = "0.11.9"
