name: stationapi

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    command: cargo watch -s "cargo run -p stationapi"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mariadb://stationapi:password@db/stationapi
      ACCEPT_HTTP1: true
      ENABLE_ALL_STATIONS_RPC: true
      HOST: 0.0.0.0
    ports:
      - 50051:50051
    networks:
      - sapi-link

  db:
    image: mariadb:11.5.2
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: stationapi
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: stationapi
    ports:
      - 3306:3306
    networks:
      - sapi-link

  migration:
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    command: ["./wait-for-it.sh", "db:3306", "--", "./migration"]
    depends_on:
      - db
    environment:
      MYSQL_USER: stationapi
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DATABASE: stationapi
    networks:
      - sapi-link

networks:
  sapi-link:
