name: stationapi

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    command: cargo watch -s "cargo run -p stationapi"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mysql://stationapi:password@db/stationapi?tcp_nodelay=true
      ACCEPT_HTTP1: true
      ENABLE_ALL_STATIONS_RPC: true
      HOST: 0.0.0.0
    ports:
      - 50051:50051
    networks:
      - sapi-link

  db:
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: stationapi
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: stationapi
    networks:
      - sapi-link

  migration:
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    command: ["./wait-for-it.sh", "db:3306", "--", "./migration"]
    depends_on:
      - db
    environment:
      MYSQL_USER: stationapi
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DATABASE: stationapi
    networks:
      - sapi-link

networks:
  sapi-link:
