name: stationapi-prod

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.prod
    depends_on:
      - db
      - migration
    environment:
      DATABASE_URL: mysql://stationapi:password@db/stationapi
      DISABLE_GRPC_WEB: false
      HOST: 0.0.0.0
    ports:
      - 50051:50051
    restart: always
    networks:
      - sapi-link

  db:
    image: mariadb:11.5.2
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_USER: stationapi
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: stationapi
    restart: always
    networks:
      - sapi-link

  migration:
    build:
      context: .
      dockerfile: ./docker/migration/Dockerfile
    command: ["./wait-for-it.sh", "db:3306", "--", "./migration"]
    depends_on:
      - db
    environment:
      MYSQL_USER: stationapi
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DATABASE: stationapi
    restart: on-failure
    networks:
      - sapi-link

networks:
  sapi-link:
