apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"my-port":"HTTP2"}'
  name: stationapi
  labels:
    app: stationapi
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 3000
    protocol: TCP
    name: my-port
  selector:
    app: stationapi
