name: Deploy to preview environment

on:
  pull_request:
  push:
    branches:
      - feature/on-premises-preview

jobs:
  deploy:
    environment: preview
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Init submodule
        run: git submodule update --init --remote
      - name: docker compose build
        run: docker compose -f ./compose.prod.yml build
